export const FONTS = [
  { label: 'Default Font', value: '' },
  { label: 'Source Han Sans', value: 'SourceHanSans' },
  { label: 'Source Han Serif', value: 'SourceHanSerif' },
  { label: 'AR PL Kaiti', value: 'WenDingPLKaiTi' },
  { label: 'AR PL Songti', value: 'WenDingPLSongTi' },
  { label: 'Zhuque FangSong', value: 'ZhuQueFangSong' },
  { label: 'LXGW WenKai', value: 'LXGWWenKai' },
  { label: 'LXGW Neo ZhiSong', value: 'LXGWNeoZhiSong' },
  { label: 'LXGW Neo XiHei', value: 'LXGWNeoXiHei' },
  { label: 'Alibaba PuHuiTi', value: 'AlibabaPuHuiTi' },
  { label: 'Deyi Hei', value: 'DeYiHei' },
  { label: 'MiSans', value: 'MiSans' },
  { label: 'Source Serif 4', value: 'SourceSerif4' },
  { label: 'JetBrains Mono', value: 'JetBrainsMono' },
  { label: 'Literata', value: 'Literata' },
  { label: 'Inter', value: 'Inter' },
  { label: 'Roboto', value: 'Roboto' },
  { label: 'Open Sans', value: 'OpenSans' },
  { label: 'Montserrat', value: 'Montserrat' },
  { label: 'Source Sans Pro', value: 'SourceSansPro' },
  { label: 'Merriweather', value: 'Merriweather' },
  { label: 'Lato', value: 'Lato' },
]