"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { Plus, Save, Trash2, Wand2 } from "lucide-react";
import { AppShell } from "@/components/layout/app-shell";
import { GOOGLE_FONT_OPTIONS } from "@/components/slide-editor/text/google-fonts";
import { createBlankHtmlTheme, parseHtmlTheme } from "@/lib/html-themes/schema.js";
import { loadHtmlTheme, saveHtmlTheme } from "@/lib/html-themes/client";
import type { HtmlTheme, HtmlThemeRecipe } from "@/lib/html-themes/types";
import { HtmlThemeThumbnail } from "./html-theme-thumbnail";

const roles = ["cover", "content", "stat", "comparison", "quote", "section", "visual", "closing"];
const compositions = ["centered", "split-left", "split-right", "editorial-right", "two-column", "metric-rail", "visual-focus", "quote-statement", "full-bleed"];

export function HtmlThemeEnginePage() {
  const router = useRouter(); const params = useSearchParams(); const id = params.get("theme");
  const [theme, setTheme] = useState<HtmlTheme | null>(null); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false); const [previewing, setPreviewing] = useState(false);
  useEffect(() => { if (!id) { setTheme(createBlankHtmlTheme({ id: "new-html-theme" } as never) as HtmlTheme); return; } loadHtmlTheme(id).then((item) => { if (item) setTheme(item); else setError("HTML theme tidak ditemukan."); }).catch((e) => setError(e instanceof Error ? e.message : "Gagal memuat theme")); }, [id]);
  const summary = useMemo(() => theme ? ({ ...theme, recipeCount: theme.recipes.length, isDefault: false, firstRecipe: theme.recipes[0]?.name ?? "" }) : null, [theme]);
  const patch = <K extends keyof HtmlTheme>(key: K, value: HtmlTheme[K]) => setTheme((current) => current ? { ...current, [key]: value } : current);
  const save = async () => { if (!theme) return; try { parseHtmlTheme(theme); setSaving(true); const saved = await saveHtmlTheme(theme, theme.updatedAt); setTheme(saved); router.replace(`/html-theme-engine?theme=${encodeURIComponent(saved.id)}`); } catch (e) { setError(e instanceof Error ? e.message : "Theme tidak valid"); } finally { setSaving(false); } };
  const preview = async () => { if (!theme?.updatedAt) return; setPreviewing(true); setError(null); try { const response = await fetch(`/api/html-themes/${encodeURIComponent(theme.id)}/preview`, { method: "POST" }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body?.error ?? "Preview gagal"); setTheme(body.theme); } catch (e) { setError(e instanceof Error ? e.message : "Preview gagal"); } finally { setPreviewing(false); } };
  if (error) return <AppShell><div className="p-10 text-red-300">{error}</div></AppShell>; if (!theme || !summary) return <AppShell><div className="p-10 text-zinc-500">Memuat…</div></AppShell>;
  return <AppShell><div className="mx-auto max-w-6xl px-8 py-8"><div className="mb-6 flex items-center justify-between"><div><Link href="/template-list?kind=html" className="text-xs text-[#a29bfe]">← HTML themes</Link><h1 className="mt-2 text-2xl font-bold text-white">HTML Theme Editor</h1><p className="mt-1 text-sm text-zinc-400">Ubah aturan yang dibaca AI, bukan elemen canvas satu per satu.</p></div><div className="flex gap-2"><button disabled={saving || previewing || !theme.updatedAt} onClick={() => void preview()} className="flex items-center gap-2 rounded-lg border border-[#2d2e42] px-3 py-2 text-sm text-zinc-200 disabled:opacity-50"><Wand2 className="h-4 w-4" />{previewing ? "Rendering…" : "Generate preview"}</button><button disabled={saving} onClick={() => void save()} className="flex items-center gap-2 rounded-lg bg-[#6c5ce7] px-3 py-2 text-sm font-medium text-white disabled:opacity-50"><Save className="h-4 w-4" />{saving ? "Saving…" : "Save theme"}</button></div></div>
    <div className="grid gap-6 lg:grid-cols-[1fr_320px]"><div className="space-y-6"><section className="rounded-xl border border-[#2d2e42] bg-[#13131f] p-5"><h2 className="font-semibold text-white">Identity</h2><div className="mt-4 grid gap-3"><input value={theme.id} disabled={theme.updatedAt !== null} onChange={(e) => patch("id", e.target.value.toLowerCase().replace(/[^a-z0-9_-]/g, "-"))} className="rounded bg-[#1a1b2e] p-2 text-sm text-white disabled:opacity-50" placeholder="theme-id"/><input value={theme.name} onChange={(e) => patch("name", e.target.value)} className="rounded bg-[#1a1b2e] p-2 text-sm text-white" placeholder="Theme name"/><textarea value={theme.description} onChange={(e) => patch("description", e.target.value)} className="rounded bg-[#1a1b2e] p-2 text-sm text-white" placeholder="Description"/></div></section>
      <section className="rounded-xl border border-[#2d2e42] bg-[#13131f] p-5"><h2 className="font-semibold text-white">Palette & typography</h2><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4">{Object.entries(theme.colors).map(([key, value]) => <label key={key} className="text-xs text-zinc-400">{key}<input value={value} onChange={(e) => patch("colors", { ...theme.colors, [key]: e.target.value })} className="mt-1 w-full rounded bg-[#1a1b2e] p-2 font-mono text-xs text-white" /></label>)}</div><div className="mt-4 grid grid-cols-3 gap-3">{(["headingFont", "bodyFont"] as const).map((key) => <select key={key} value={theme.typography[key]} onChange={(e) => patch("typography", { ...theme.typography, [key]: e.target.value })} className="rounded bg-[#1a1b2e] p-2 text-sm text-white">{GOOGLE_FONT_OPTIONS.map((font) => <option key={font.family}>{font.family}</option>)}</select>)}<select value={theme.typography.scale} onChange={(e) => patch("typography", { ...theme.typography, scale: e.target.value as HtmlTheme["typography"]["scale"] })} className="rounded bg-[#1a1b2e] p-2 text-sm text-white"><option>compact</option><option>balanced</option><option>expressive</option></select></div></section>
      <section className="rounded-xl border border-[#2d2e42] bg-[#13131f] p-5"><h2 className="font-semibold text-white">Art direction</h2><textarea value={theme.guidance.artDirection} onChange={(e) => patch("guidance", { ...theme.guidance, artDirection: e.target.value })} className="mt-4 min-h-28 w-full rounded bg-[#1a1b2e] p-3 text-sm text-white" placeholder="Visual rules for the AI…" /></section>
      <section className="rounded-xl border border-[#2d2e42] bg-[#13131f] p-5"><div className="flex items-center justify-between"><h2 className="font-semibold text-white">Layout recipes</h2><button onClick={() => patch("recipes", [...theme.recipes, { ...theme.recipes[0], id: `recipe-${theme.recipes.length + 1}`, name: "New recipe", roles: ["content"] }])} className="flex gap-1 text-xs text-[#a29bfe]"><Plus className="h-4 w-4" />Add recipe</button></div><div className="mt-4 space-y-3">{theme.recipes.map((recipe, index) => <RecipeEditor key={`${recipe.id}-${index}`} recipe={recipe} onChange={(next) => patch("recipes", theme.recipes.map((item, itemIndex) => itemIndex === index ? next : item))} onDelete={() => theme.recipes.length > 1 && patch("recipes", theme.recipes.filter((_, itemIndex) => itemIndex !== index))} />)}</div></section>
    </div><aside className="h-fit rounded-xl border border-[#2d2e42] bg-[#13131f] p-4"><h2 className="mb-3 text-sm font-semibold text-white">Live token preview</h2><div className="aspect-video overflow-hidden rounded"><HtmlThemeThumbnail theme={summary} /></div><p className="mt-3 text-xs leading-relaxed text-zinc-500">Preview ini menunjukkan token visual. Saat deck dibuat, AI mengikuti recipe yang sesuai dengan peran slide.</p></aside></div></div></AppShell>;
}

function RecipeEditor({ recipe, onChange, onDelete }: { recipe: HtmlThemeRecipe; onChange: (recipe: HtmlThemeRecipe) => void; onDelete: () => void }) {
  return <div className="rounded-lg border border-[#2d2e42] p-3"><div className="flex gap-2"><input value={recipe.name} onChange={(e) => onChange({ ...recipe, name: e.target.value })} className="min-w-0 flex-1 rounded bg-[#1a1b2e] p-2 text-sm text-white"/><button onClick={onDelete} className="text-red-300"><Trash2 className="h-4 w-4" /></button></div><div className="mt-2 flex flex-wrap gap-2">{roles.map((role) => <label key={role} className="text-[11px] text-zinc-400"><input type="checkbox" checked={recipe.roles.includes(role as never)} onChange={() => onChange({ ...recipe, roles: recipe.roles.includes(role as never) ? recipe.roles.filter((item) => item !== role) : [...recipe.roles, role as never] })} /> {role}</label>)}</div><select value={recipe.composition} onChange={(e) => onChange({ ...recipe, composition: e.target.value })} className="mt-2 rounded bg-[#1a1b2e] p-2 text-xs text-white">{compositions.map((entry) => <option key={entry}>{entry}</option>)}</select><textarea value={recipe.instructions} onChange={(e) => onChange({ ...recipe, instructions: e.target.value })} className="mt-2 min-h-20 w-full rounded bg-[#1a1b2e] p-2 text-xs text-white" placeholder="Specific layout rules for AI" /></div>;
}
